### ISSUE TITLE
No sound in chrome?

### ISSUE THREAD

**Issue by robtec** [azer/radio-paradise-api#2]
Hi,

I browsed to http://listenparadise.org/ using chrome, but there is no sound?

![screen shot 2018-05-14 at 10 56 16](https://user-images.githubusercontent.com/8657653/39990804-7438f368-5765-11e8-9d63-04f0fb05339d.png)

The speaker icon means it playing right?

**Comment by azer** [comment]
Weird, can you try tapping the sound button ? Can you also share network logs in the dev tools ?

**Comment by jamescgoff** [comment]
Not sure if it's the same issue, but earlier in Chrome I was getting an Autoplay Policy error in the console. I played around with a bunch of things, and it's working for me now. Honestly not sure what changed to make it work again.
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by what** [comment]
[player]: PlayMsg
(index):28 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
forcePlay

Chrome's Autoplay Policy

**Comment by azer** [comment]
Makes sense. I guess it needs a play button to trigger play

**Comment by robtec** [comment]
Shall I close?

**Comment by azer** [comment]
Can you all try again @what @robtec ? I just released a patch; https://github.com/azer/radio-paradise/commit/aed046e1300bad9aedfa77b89bd0f96387903beb

**Comment by what** [comment]
Seems to be working just fine after the patch. Looks great, thanks for building it!

**Comment by azer** [comment]
thanks for the help!
