### ISSUE TITLE
listenparadise.org is down

### ISSUE THREAD

**Issue by gskoljarev** [azer/radio-paradise-api#4]
Was it a planned shutdown?

**Comment by azer** [comment]
domain must be expired, I'll renew it

**Comment by gskoljarev** [comment]
Much appreciated.

Love the site btw, minimalism of the design is just perfect.

**Comment by azer** [comment]
thanks, should be fixed now

**Comment by gskoljarev** [comment]
Hi @azer, the site is down again.

**Comment by azer** [comment]
Thanks for the heads up @gskoljarev . The domain is expired, give me some time to think about potential solutions for its cost

**Comment by gskoljarev** [comment]
Thanks for info @azer - let me know if I can support in any way.

Could you share and break down cost components (like hosting, domain, API access...)?
